// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (ACCESSTOKEN, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (SESSION, error)
	GetAccessToken(ctx context.Context, accessTokenID uuid.UUID) (ACCESSTOKEN, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (SESSION, error)
}

var _ Querier = (*Queries)(nil)
