// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AUTHOR struct {
	ID        uuid.UUID    `json:"id"`
	FullName  string       `json:"full_name"`
	Birthdate sql.NullTime `json:"birthdate"`
	CreatedAt time.Time    `json:"created_at"`
}

type BOOK struct {
	ID              uuid.UUID      `json:"id"`
	Title           string         `json:"title"`
	FullTitle       string         `json:"full_title"`
	Publisher       uuid.UUID      `json:"publisher"`
	PublicationDate time.Time      `json:"publication_date"`
	Isbn            string         `json:"isbn"`
	Description     sql.NullString `json:"description"`
	Price           float64        `json:"price"`
	StockQuantity   int32          `json:"stock_quantity"`
	FrontCoverImage sql.NullString `json:"front_cover_image"`
	BackCoverImage  sql.NullString `json:"back_cover_image"`
	CreatedAt       time.Time      `json:"created_at"`
}

type BOOKAUTHOR struct {
	BookID    uuid.UUID `json:"book_id"`
	AuthorID  uuid.UUID `json:"author_id"`
	CreatedAt time.Time `json:"created_at"`
}

type BOOKGENRE struct {
	BookID    uuid.UUID `json:"book_id"`
	GenreID   uuid.UUID `json:"genre_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GENRE struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PUBLISHER struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	CreatedAt time.Time      `json:"created_at"`
}
