// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (USER, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (USER, error)
	GetUserByName(ctx context.Context, username string) (USER, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]USER, error)
}

var _ Querier = (*Queries)(nil)
