// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddNewDiscount(ctx context.Context, arg AddNewDiscountParams) (DISCOUNT, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (ORDER, error)
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (ORDERDETAIL, error)
	CreateShoppingCartItem(ctx context.Context, arg CreateShoppingCartItemParams) (SHOPPINGCARTITEM, error)
	GetDiscount(ctx context.Context, discountID uuid.UUID) (DISCOUNT, error)
	GetOrder(ctx context.Context, orderID uuid.UUID) (ORDER, error)
	GetOrderDetail(ctx context.Context, arg GetOrderDetailParams) (ORDERDETAIL, error)
	GetShoppingCartItem(ctx context.Context, cartItemID uuid.UUID) (SHOPPINGCARTITEM, error)
	ListDiscounts(ctx context.Context, arg ListDiscountsParams) ([]DISCOUNT, error)
	ListOrderDetails(ctx context.Context, arg ListOrderDetailsParams) ([]ORDERDETAIL, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ORDER, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) (ORDER, error)
	ListShoppingCartItemsByUser(ctx context.Context, arg ListShoppingCartItemsByUserParams) ([]SHOPPINGCARTITEM, error)
}

var _ Querier = (*Queries)(nil)
