// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddNewDiscount(ctx context.Context, arg AddNewDiscountParams) (DISCOUNT, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (ORDER, error)
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (ORDERDETAIL, error)
	CreateShoppingCartItem(ctx context.Context, arg CreateShoppingCartItemParams) (SHOPPINGCARTITEM, error)
	GetDiscount(ctx context.Context, discountID uuid.UUID) (DISCOUNT, error)
	GetOrder(ctx context.Context, orderID uuid.UUID) (GetOrderRow, error)
	GetOrderDetail(ctx context.Context, arg GetOrderDetailParams) (ORDERDETAIL, error)
	GetShoppingCartItemByUser(ctx context.Context, arg GetShoppingCartItemByUserParams) (SHOPPINGCARTITEM, error)
	GetShoppingCartItemByUserForUpdate(ctx context.Context, arg GetShoppingCartItemByUserForUpdateParams) (SHOPPINGCARTITEM, error)
	ListDiscounts(ctx context.Context, arg ListDiscountsParams) ([]DISCOUNT, error)
	ListOrderDetails(ctx context.Context, arg ListOrderDetailsParams) ([]ORDERDETAIL, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListShoppingCartItemsByUser(ctx context.Context, arg ListShoppingCartItemsByUserParams) ([]SHOPPINGCARTITEM, error)
	UpdateShoppingCartItemListStatus(ctx context.Context, arg UpdateShoppingCartItemListStatusParams) ([]SHOPPINGCARTITEM, error)
	UpdateShoppingCartItemQuantity(ctx context.Context, arg UpdateShoppingCartItemQuantityParams) (SHOPPINGCARTITEM, error)
	UpdateShoppingCartItemStatus(ctx context.Context, arg UpdateShoppingCartItemStatusParams) (SHOPPINGCARTITEM, error)
}

var _ Querier = (*Queries)(nil)
